blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/H33rRDTm3p
    about: Please ask any questions here
  - name: Enterprise Questions
    url: opensource@getsynth.com
    about: Please get in touch for any enterprise related questions